---
title: "Billboard 100 Wrangling"
output: html_notebook
date: "2021-10-06"
---

```{r setup, include = FALSE}
library(tidyverse)
```

## Import the data

The CSV files are quite large so I downloaded them rather than pulling them down each time I import. They're available on the [TidyTuesday repo](https://github.com/rfordatascience/tidytuesday/tree/master/data/2021/2021-09-14). 

### Billboard charts and Spotify audio features.
```{r import}
billboard <- readr::read_csv("billboard.csv")
audio_features <- readr::read_csv("audio_features.csv")
```

## Tidy the data

For the "audio features" we're only interested in the genres.

```{r table-of-genres }
knitr::kable(
  audio_features %>% select(spotify_genre) %>% head(5)
)
```

A table with a row for each song / genre combo. Songs with no genres do not have an entry.

```{r song_genre-table }
songs_genres <- audio_features %>%
  select(song_id, spotify_genre) %>%
  mutate(
    genre = str_extract_all(spotify_genre, "(?<=')[a-z ]+(?=')")
  ) %>%
  select(-spotify_genre) %>%
  unnest(genre)
```

```{r new-join-table }
knitr::kable(
  songs_genres %>% head(20)
)
```
